"""Change FileMetadata id to file_id

Revision ID: 149e78bc7b69
Revises: c33ca3b8ce5c
Create Date: 2025-04-14 17:52:22.896784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149e78bc7b69'
down_revision: Union[str, None] = 'c33ca3b8ce5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('file_id', sa.String(), nullable=False))
    op.drop_column('file_metadata', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('file_metadata', 'file_id')
    # ### end Alembic commands ###
